<?php


namespace nickdnk\Klaviyo\Tests;

use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Response;
use nickdnk\Klaviyo\APIClient;
use nickdnk\Klaviyo\Exceptions\ClientException;
use nickdnk\Klaviyo\Exceptions\KlaviyoError;
use nickdnk\Klaviyo\Exceptions\ServerException;
use nickdnk\Klaviyo\Resources\Shared\IdentifiableResource;
use nickdnk\Klaviyo\Resources\Shared\Relationship;
use nickdnk\Klaviyo\Resources\Shared\Resource;
use nickdnk\Klaviyo\Resources\TypeRegistry;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use ReflectionClass;

/**
 * Replays real Klaviyo responses recorded during the live smoke run (tests/fixtures/responses,
 * generated by scratch/fixtures.php) through the SDK's hydration and error mapping. Hand-written
 * mocks encode what we *think* the API returns; this corpus encodes what it *did* return, so a
 * shape the SDK cannot hydrate, a `type` missing from the TypeRegistry or an attribute a Response
 * class does not document fails here instead of in production.
 *
 * Refresh: run the smoke suites with SMOKE_RECORD=1, then `php scratch/fixtures.php --clean`.
 */
class RecordedResponsesTest extends TestCase
{

    private const string DIR = __DIR__ . '/fixtures/responses';

    public static function fixtures(): iterable
    {

        foreach (glob(self::DIR . '/*.json') ?: [] as $file) {
            yield basename($file, '.json') => [json_decode(file_get_contents($file), true)];
        }

    }

    public static function successFixtures(): iterable
    {

        foreach (self::fixtures() as $name => [$f]) {
            if ($f['response']['status'] < 300 && is_array($f['response']['body']) && array_key_exists('data', $f['response']['body'])) {
                yield $name => [$f];
            }
        }

    }

    public static function errorFixtures(): iterable
    {

        foreach (self::fixtures() as $name => [$f]) {
            if ($f['response']['status'] >= 400) {
                yield $name => [$f];
            }
        }

    }

    public function testCorpusExists(): void
    {

        self::assertNotEmpty(iterator_to_array(self::fixtures()), 'tests/fixtures/responses is empty — run the smoke suites with SMOKE_RECORD=1 and scratch/fixtures.php');

    }

    #[DataProvider('successFixtures')]
    public function testSuccessfulResponseHydrates(array $f): void
    {

        $result = APIClient::hydrateResponse($f['response']['body']);
        self::assertArrayHasKey('links', $result);

        $raw = $f['response']['body']['data'];
        if ($raw === null) {
            self::assertNull($result['data'], "{$f['operation']}: empty to-one relation stays null");
            return;
        }
        $items = is_array($result['data']) && array_is_list($result['data']) ? $result['data'] : [$result['data']];
        $rawItems = array_is_list($raw) ? $raw : [$raw];

        foreach ($items as $i => $item) {
            $rawType = $rawItems[$i]['type'] ?? null;
            $class = TypeRegistry::resolve((string)$rawType);
            self::assertNotNull($class, "type \"{$rawType}\" returned by {$f['operation']} is not registered in TypeRegistry");
            self::assertInstanceOf($class, $item, "{$f['operation']}: item {$i}");
            self::assertInstanceOf(IdentifiableResource::class, $item);
            if (isset($rawItems[$i]['id'])) {
                self::assertSame((string)$rawItems[$i]['id'], $item->id);
            }
            $this->assertAttributesDocumented($item, $rawItems[$i]['attributes'] ?? [], $f['operation']);
            foreach ($rawItems[$i]['relationships'] ?? [] as $name => $rel) {
                self::assertInstanceOf(Relationship::class, $item->getRelationship($name), "{$f['operation']}: relationship {$name} lost in hydration");
            }
            // round trip: every attribute Klaviyo sent must survive serialisation (nulls and empty arrays excepted by design)
            $reserialised = $item->jsonSerialize()['attributes'] ?? [];
            foreach ($rawItems[$i]['attributes'] ?? [] as $k => $v) {
                if ($v === null || $v === [] || (is_array($v) && self::isDeepEmpty($v))) {
                    continue;
                }
                self::assertArrayHasKey($k, $reserialised, "{$f['operation']}: attribute {$k} dropped on re-serialisation");
            }
        }

        foreach ($result['included'] ?? [] as $inc) {
            self::assertInstanceOf(IdentifiableResource::class, $inc);
        }
        foreach ($f['response']['body']['included'] ?? [] as $inc) {
            self::assertNotNull(TypeRegistry::resolve($inc['type']), "included type \"{$inc['type']}\" ({$f['operation']}) is not registered in TypeRegistry");
        }

    }

    #[DataProvider('errorFixtures')]
    public function testErrorResponseMaps(array $f): void
    {

        $request = new Request($f['request']['method'], 'https://a.klaviyo.com' . $f['request']['path']);
        $body = is_array($f['response']['body']) ? json_encode($f['response']['body']) : (string)$f['response']['body'];
        $response = new Response($f['response']['status'], ['Content-Type' => $f['response']['headers']['content-type'] ?? 'application/vnd.api+json'], $body);

        if ($f['response']['status'] >= 500) {
            $e = new ServerException($response);
            self::assertSame($f['response']['status'], $e->getHttpStatus());
            return;
        }

        $e = new ClientException($request, $response);
        self::assertSame($f['response']['status'], $e->getHttpStatus());
        if (is_array($f['response']['body']) && isset($f['response']['body']['errors'])) {
            self::assertNotEmpty($e->getErrors(), "{$f['operation']}: errors array not parsed");
            foreach ($e->getErrors() as $err) {
                self::assertInstanceOf(KlaviyoError::class, $err);
                self::assertNotNull($err->code ?? $err->title ?? $err->detail, 'error has at least one descriptive field');
            }
            self::assertStringContainsString((string)($e->getFirstError()->detail ?? $e->getFirstError()->title), $e->getMessage());
        }

    }

    /**
     * Every attribute Klaviyo actually sent must be documented as an @property on the Response
     * class (or a parent), so IDEs and readers can trust the docblocks. Free-form bags are exempt.
     */
    private function assertAttributesDocumented(Resource $item, array $attributes, string $operation): void
    {

        $documented = self::documentedProperties($item::class);
        if ($documented === null) {
            return; // class opted out (AttributeBag-like free-form resources)
        }
        $missing = array_values(array_diff(array_keys($attributes), $documented));
        self::assertSame([], $missing, sprintf('%s: %s returns attributes not documented on %s: %s', $operation, $item::class, basename(str_replace('\\', '/', $item::class)), implode(', ', $missing)));

    }

    /** @var array<class-string, list<string>|null> */
    private static array $docCache = [];

    /**
     * @return list<string>|null null when the class or a parent is a free-form bag (documents `@property mixed $*`)
     */
    private static function documentedProperties(string $class): ?array
    {

        if (array_key_exists($class, self::$docCache)) {
            return self::$docCache[$class];
        }
        $props = [];
        for ($rc = new ReflectionClass($class); $rc; $rc = $rc->getParentClass()) {
            $doc = $rc->getDocComment() ?: '';
            if (preg_match('/@property[^\n]*\$\*|free-form/i', $doc) && str_contains($rc->getShortName(), 'Bag')) {
                return self::$docCache[$class] = null;
            }
            preg_match_all('/@property(?:-read)?\s+.*?\$(\w+)/', $doc, $m);
            $props = [...$props, ...$m[1]];
        }

        return self::$docCache[$class] = array_values(array_unique($props));

    }

    private static function isDeepEmpty(array $v): bool
    {

        foreach ($v as $x) {
            if (!(is_array($x) ? self::isDeepEmpty($x) : $x === null)) {
                return false;
            }
        }

        return true;

    }

}
